name: Deploy new site data for GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'metadata/**'
      - 'streams/**'
      - 'site_data/**'
      - 'validation-results.json'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0  # Get all history for proper deployment
          
      - name: Set up Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Generate site data (with validation)
        run: |
          echo "Generating site data using validation results..."
          python scripts/generate_site_data.py
          
      - name: Commit updated metadata
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add metadata/ docs/site_data/ validation-results.json
          git commit -m "Update metadata catalog and site data" || echo "No changes to commit"
          git push || echo "No changes to push"
          echo "Successfully committed and pushed changes."