name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'metadata/**'
      - 'streams/**'
      - 'site_data/**'
      - 'validation-results.json'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get all history for proper deployment
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Generate site data (without validation)
        run: python scripts/generate_site_data.py
        
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          clean: true
          
      - name: Commit updated metadata
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add metadata/ site_data/
          git commit -m "Update metadata catalog and site data" || echo "No changes to commit"
          git push
