name: Generate Metadata Catalog

on:
  schedule:
    - cron: '0 0 * * 3'  # Run weekly on Wednesday
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-catalog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Generate metadata catalog
        run: |
          echo "Generating metadata catalog..."
          python scripts/generate_site_data.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes
          if [[ -n $(git status --porcelain metadata/ site_data/) ]]; then
            git add metadata/ site_data/
            git commit -m "Update metadata catalog [automated]"
            git push
            echo "Metadata catalog updated and committed"
          else
            echo "No changes to metadata catalog"
          fi