name: Validate Streams

on:
  schedule:
    - cron: '0 0 * * 0' 
  workflow_dispatch:
  pull_request:
    paths:
      - 'streams/**'
      - 'metadata/**'

jobs:
  validate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Validate streams
        run: python scripts/validate_streams.py
      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('validation-results.json', 'utf8'));
            const comment = `## Validation des flux\n${results.summary}\n\n${results.details}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });